# What is a Python library? Why do we use Python libraries?

## A Python library is a collection of modules and packages that provide pre-written code to perform common tasks. 
## Libraries in Python can include functions, classes, and variables that can be reused in different programs to perform specific tasks without needing to write code from scratch.
<!-- Python libraries are distributed in a variety of formats, such as single modules (e.g., a single .py file) or packages (e.g., directories containing multiple modules along with __init__.py files). Some well-known Python libraries include numpy for numerical computing, pandas for data analysis, requests for making HTTP requests, and matplotlib for data visualization. -->

# Python libraries are used for several reasons:
# Code Reusability and Efficiency:
# Simplification of Complex Tasks
# Consistency and Reliability

# 2. What is the difference between Numpy array and List?
# A NumPy array is a fixed-size, homogeneous data structure optimized for numerical computations, providing efficient storage and operations on numerical data. A Python list is a flexible, dynamic-sized, heterogeneous data structure that can hold different data types but is less efficient for numerical and large-scale computations.

In [2]:
import numpy as np

In [5]:
# #3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]
arr= [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
np.shape(arr)

(3, 4)

In [10]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
array[0]

array([1, 2, 3, 4])

In [9]:
# How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Accessing the element at the third row and fourth column
element = array[2, 3]
print(element)  # Output: 12

12


In [11]:
# Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
odd_indexed_elements = array[1::2, 1::2]

print(odd_indexed_elements)

[[6 8]]


In [13]:
# How can you generate a random 3x3 matrix with values between 0 and 1?

arr= np.random.rand(3, 3)
arr

array([[0.91900696, 0.53754796, 0.93799235],
       [0.49838258, 0.28903996, 0.49055261],
       [0.76145389, 0.04463831, 0.60049256]])

In [14]:
#Describe the difference between np.random.rand and np.random.randn?
# Generate a 3x3 matrix with uniform random values between 0 and 1
random_uniform = np.random.rand(3, 3)
print(random_uniform)

# Generate a 3x3 matrix with standard normal random values
random_normal = np.random.randn(3, 3)
print(random_normal)

[[0.02539998 0.96873367 0.15003867]
 [0.65275262 0.6055597  0.96115551]
 [0.35577825 0.53162346 0.15754449]]
[[-0.91791927  0.79275263  0.40422596]
 [ 0.80744399  0.24769876  0.66974243]
 [ 1.14035357 -1.06896791  0.11628125]]


In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

expanded_array = np.expand_dims(array, axis=0)  
print(expanded_array)
print("Shape of expanded array:", expanded_array.shape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape of expanded array: (1, 3, 4)


In [2]:
# How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])


transposed_array = array.T

print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
